name: Octoherd

on:
  workflow_dispatch:
    inputs: 
      options:
        description: 'Script options, e.g.: --topics my-topic --topics my-other-topic '
        required: false
        type: string
        default: ''
      script:
        description: 'Script, e.g.: octoherd-script-replace-all-repository-topics'
        required: true
        type: string

jobs:
  run-octoherd-script:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup Node'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: 'Inject slug/short variables'
        uses: rlespinasse/github-slug-action@v4.x
      - run: |
          npx $SCRIPT $SCRIPT_OPTIONS -T $TOKEN -R $REPO_SLUG --octoherd-bypass-confirms
        env:
          SCRIPT: ${{ github.event.inputs.script }}
          SCRIPT_OPTIONS: ${{ github.event.inputs.options }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_SLUG: ${{ env.GITHUB_REPOSITORY }}
